### ISSUE TITLE
Is the CityGML writer plan ?

### ISSUE THREAD

**Issue by alavenant** [jklimke/libcitygml#40]
I'm using CityGML for years with my own I/O library, which is not complete and aging. But I have no time to ameliorate it today. I test your reader which is performing. But I need the writher too. Is it plan ?

**Comment by jklimke** [comment]
There is currently no immediate plan to extend the library towards write functionalities, since there is no immediate need for that on my side right now. But this would surely make sense. Nevertheless, there is some complexity involved in writing out a correct CityGML document since, e.g., the geometry data is kind of transformed and optimized during read.

If anybody is willing to contribute a first approach for writing CityGML documents out of the library's object model, feel free to contribute.

There are further approaches for storing citygml models encoded  as JSON, which may be another good serialization target for the library. http://www.cityjson.org/en/0.1/

**Comment by alavenant** [comment]
Thanks for your reply.

I do not know the CityJSON software. I like the approach of JSON which is easier writable ans readable than XML. I will test this approach.
